#!/usr/bin/env perl
use strict;
use warnings;
use File::Path qw(remove_tree);

# Text2SIP uninstall helper.
# Current releases do not install or operate a Mosquitto bridge. The cleanup
# below only removes Text2SIP-owned runtime state and legacy bridge artifacts
# that may exist after upgrading from an older plugin version.

my @legacy_files = (
    '/etc/mosquitto/conf.d/30-bridge-t2s.conf',
    '/etc/mosquitto/role/sip-bridge',
    '/etc/mosquitto/sip-uninstall.pl',
);

my $mosquitto_changed = 0;
for my $file (@legacy_files) {
    next unless -e $file;
    if (unlink $file) {
        print "Removed legacy Text2SIP file: $file\n";
        $mosquitto_changed = 1 if $file =~ m{^/etc/mosquitto/};
    } else {
        warn "Could not remove $file: $!\n";
    }
}

my $legacy_cert_dir = '/etc/mosquitto/certs/sip-bridge';
if (-d $legacy_cert_dir) {
    remove_tree($legacy_cert_dir, { error => \my $err });
    if (@$err) {
        warn "Could not completely remove $legacy_cert_dir\n";
    } else {
        print "Removed legacy Text2SIP certificate directory: $legacy_cert_dir\n";
        $mosquitto_changed = 1;
    }
}

# Restore Mosquitto files which old Text2SIP bridge versions disabled.
# /etc/mosquitto/ca and mosq-ca.crt are deliberately left untouched because
# the CA can be shared with Text2Speech or other Mosquitto clients.
my @restore_pairs = (
    ['/etc/mosquitto/conf.d/mosq_mqttgateway.conf.disabled', '/etc/mosquitto/conf.d/mosq_mqttgateway.conf'],
    ['/etc/mosquitto/conf.d/mosq_passwd.disabled',          '/etc/mosquitto/conf.d/mosq_passwd'],
    ['/etc/mosquitto/conf.d/disabled/mosq_mqttgateway.conf','/etc/mosquitto/conf.d/mosq_mqttgateway.conf'],
    ['/etc/mosquitto/conf.d/disabled/mosq_passwd',         '/etc/mosquitto/conf.d/mosq_passwd'],
);
for my $pair (@restore_pairs) {
    my ($src, $dst) = @$pair;
    next unless -e $src;
    if (!-e $dst) {
        if (rename $src, $dst) {
            print "Restored Mosquitto config: $dst\n";
        } else {
            warn "Could not restore $src to $dst: $!\n";
            next;
        }
    } else {
        if (unlink $src) {
            print "Removed obsolete disabled duplicate: $src\n";
        } else {
            warn "Could not remove $src: $!\n";
            next;
        }
    }
    $mosquitto_changed = 1;
}
rmdir '/etc/mosquitto/conf.d/disabled' if -d '/etc/mosquitto/conf.d/disabled';

my $state_dir = '/var/lib/text2sip';
if (-d $state_dir) {
    remove_tree($state_dir, { error => \my $err });
    warn "Could not completely remove $state_dir\n" if @$err;
}

if ($mosquitto_changed) {
    system('/bin/systemctl', 'restart', 'mosquitto');
}

exit 0;
